services:
  meshtastic-mqtt:
    container_name: meshtastic-mqtt
    # Eğer env dosyasında COMPOSE_BUILD tanımlıysa klasörden derler, yoksa imaj arar
    build: ${COMPOSE_BUILD_PATH:-.} 
    image: ${MQTT_IMAGE_NAME:-lokal-meshtastic-map}
    restart: ${RESTART_POLICY:-no}
    depends_on:
      database:
        condition: service_healthy
    command: >
      sh -c "node src/mqtt.js $$MQTT_OPTS"
    environment:
      - DATABASE_URL=mysql://root:password@database:3306/meshtastic-map
      - MQTT_OPTS=${MQTT_OPTS}

  meshtastic-map:
    container_name: meshtastic-map
    build: ${COMPOSE_BUILD_PATH:-.}
    image: ${MAP_IMAGE_NAME:-lokal-meshtastic-map}
    restart: ${RESTART_POLICY:-no}
    depends_on:
      database:
        condition: service_healthy
    command: node src/index.js
    ports:
      - 34970:8080
    environment:
      - DATABASE_URL=mysql://root:password@database:3306/meshtastic-map
      - MAP_OPTS=

  database:
    container_name: database
    image: bitnami/mariadb
    restart: ${RESTART_POLICY:-no}
    ports:
      - 3306:3306
    environment:
      - MARIADB_DATABASE=meshtastic-map
      - MARIADB_ROOT_PASSWORD=password
    volumes:
      - database_data:/bitnami/mariadb
    healthcheck:
      test: ['CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh']
      interval: 10s
      timeout: 5s
      retries: 5

  db-admin:
    container_name: db-admin
    image: adminer
    restart: ${RESTART_POLICY:-no}
    ports:
      - 8081:8080
    depends_on:
      - database
      
volumes:
  database_data: